---
- name: "Install | nginx"
  apt:
    pkg: nginx-full

- name: "Configure | Create /srv/www"
  ansible.builtin.file:
    path: /srv/www
    state: directory
    mode: '0755'

- name: "Configure | install nginx config"
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/conf.d/{{ inventory_hostname }}.conf"
    mode: 0644

- name: "System | (re)start nginx service"
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes
