---
- name: "Goal | set up example.com"
  hosts: example.com
  vars:
    wp_db_name: wordpress
    wp_db_user: wordpress
    wp_db_password: "CHANGEME"
    certbot_email: "CHANGEME"
  user: root
  roles:
    - certbot
    - nginx
    - mysql
    - wordpress
