---
- name: "Install | php"
  apt:
    pkg:
      - php8.2
      - php8.2-mysql
      - php8.2-gd
      - php8.2-ssh2
      - php8.2-mcrypt
      - php8.2-curl
      - php8.2-intl
      - php8.2-mbstring
      - php8.2-soap
      - php8.2-xml
      - php8.2-xmlrpc
      - php8.2-zip
      - php8.2-fpm

- name: "System | (re)start php service"
  ansible.builtin.systemd:
    name: php8.2-fpm
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: "Register | Check if WordPress directory exists in /srv/www"
  stat: path="/srv/www/{{ inventory_hostname }}"
  register: check_path

- name: "Register | Create temporary directory"
  ansible.builtin.tempfile:
    state: directory
    suffix: wp
  register: tmp_wp

- name: "Install | Download and unpack latest WordPress"
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "{{ tmp_wp.path }}"
    remote_src: yes
    creates: "{{ tmp_wp.path }}/wordpress/"
  when: not check_path.stat.exists

- name: "Install | Move WordPress install files"
  command: "mv {{ tmp_wp.path }}/wordpress /srv/www/{{ inventory_hostname }}"
  become: yes
  when: not check_path.stat.exists

- name: "Configure | Set ownership"
  file:
    path: "/srv/www/{{ inventory_hostname }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  when: not check_path.stat.exists

- name: "Configure | Set permissions for directories"
  shell: "/usr/bin/find /srv/www/{{ inventory_hostname }}/ -type d -exec chmod 750 {} \\;"
  when: not check_path.stat.exists

- name: "Configure | Set permissions for files"
  shell: "/usr/bin/find /srv/www/{{ inventory_hostname }}/ -type f -exec chmod 640 {} \\;"
  when: not check_path.stat.exists

- name: "Install | wp-config.php"
  template:
    src: "wp-config.php.j2"
    dest: "/srv/www/{{ inventory_hostname }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: 0640
  when: not check_path.stat.exists
