---
- name: "Install | sql"
  apt:
    pkg:
      - mysql-server
      - python3-mysqldb

- name: "System | disable nginx service"
  ansible.builtin.systemd:
    name: nginx
    state: stopped
    enabled: no
    daemon_reload: yes

- name: "Configure | Create wordpress mysql user"
  become: true
  mysql_user:
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ wp_db_user }}"
    priv: "*.*:ALL"

- name: "Configure | Create wordpress mysql database"
  become: true
  mysql_db:
    login_user: root
    name: "{{ wp_db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: "Configure | Fix wordpress user auth and privileges"
  become: true
  mysql_query:
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    query:
      - ALTER USER %(user)s@'localhost' IDENTIFIED WITH mysql_native_password BY %(password)s
      - GRANT ALL ON `%(db)s`.* TO %(user)s@localhost
      - FLUSH PRIVILEGES
    named_args:
      db: "{{ wp_db_name }}"
      user: "{{ wp_db_user }}"
      password: "{{ wp_db_password }}"

- name: "Configure | Delete anonymous MySQL server user for $inventory_hostname"
  become: true
  mysql_user:
    login_user: root
    user: ""
    host: "{{ inventory_hostname }}"
    state: "absent"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: "Configure | Delete anonymous MySQL server user for localhost"
  become: true
  mysql_user:
    login_user: root
    user: ""
    state: "absent"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: "Configure | Remove the MySQL test database"
  become: true
  mysql_db:
    login_user: root
    db: test
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
