- name: "Install | certbot"
  apt:
    pkg:
      - certbot
      - python3-certbot-nginx

- name: "Configure | register certbot"
  shell: |
    certbot -n register --agree-tos --email {{ certbot_email }}
    touch /etc/letsencrypt/.registered
  args:
    creates: /etc/letsencrypt/.registered

- name: "Install | certbot certificate"
  command: 'certbot -n --nginx certonly -d {{ inventory_hostname }}'
  args:
    creates: '/etc/letsencrypt/live/{{ inventory_hostname }}'
  ignore_errors: true
